### ISSUE TITLE
CNW EXPENSE & JE 

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#13]
Cabang Palembang ada request minta ubah settingan kertas kwitansinya
apakah bisa di setting dr cnwnya?
karena tidak presisi dengan form yg digunakan cabang palembang
 
![Uploading sss.jpg…]()

**Comment by andyut** [comment]
formnya kaya gimana

**Comment by DikaAnggara89** [comment]
saya kirim di wasap pak ., ga bs ngirim foto disini error mulu

**Comment by andyut** [comment]
miscom
