### ISSUE TITLE
CNW INV-AR (CNW Colo) - Invoice Detail

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#14]
Tarik Data Penjualan Detail
Firman Semarang : 
Untuk data seminggu ke belakang lumayan lancar pak. Tapi, tetap agak lama. Untuk data 2 mingguan ke belakang itu yang sering gagal loading pak

**Comment by andyut** [comment]
dicoba lagi .. masih sama atau tidak

**Comment by andyut** [comment]
suruh coba lagi @DikaAnggara89

**Comment by andyut** [comment]
tunning SQL
