### ISSUE TITLE
CNW INV-AR  ( CABANG )

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#19]
Masukan dari cabang Bali 
Untuk CNW INV-AR

Untuk tabel kwitansi detail nya bisa di atur lagi untuk size nya yaa ?? biar keliatan rapi tanggalnya trus untuk alamat ship to nya juga masih error false 

 untuk kwitansi nya, size font untuk rekening bisa dibesarkan lagi sdikit biar lebih jelas pak
![WhatsApp Image 2021-12-09 at 9 39 03 AM](https://user-images.githubusercontent.com/8219193/145327762-189d80fe-48c2-42c9-a2a0-bcfa5bbb99e2.jpeg)

**Comment by andyut** [comment]
done
