### ISSUE TITLE
Data PIB tidak boleh manual

### ISSUE THREAD

**Issue by intanyunilasari** [andyut/cnw_project#3]
Akan membuatkan cara sehingga waktu IGU mengetik P.I.B maka, nomer  invoice - container number - amount sdb otomatis terupload dari PO (data kita) ke form PIB online.

**Comment by andyut** [comment]
- [ ] HS 
- [ ] PI
- [ ] Purchase Request
- [ ] Whempi Online
- [ ] Link PI to PO
- [ ] Link HS to Item Master
