### ISSUE TITLE
SAP WEB Inventory Transfer

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#31]
dari 5 internal transfer tokotani sudah bisa posted 3 sisa 2 lg , bu feybe masing croscek item satu persatu di gudang wh agar bisa di pindah ke outlet TTI masing masing
untuk kedepannya masih blm tau tetep bu feybe yang input internal transfer atau geri sales tokotaninya ?

**Comment by andyut** [comment]
geri pindahin , bu feybe yang posting
