### ISSUE TITLE
Check VA norek dan status

### ISSUE THREAD

**Issue by andyut** [andyut/cnw_project#37]
Check VA norek dan status
![WhatsApp Image 2022-02-24 at 2 41 25 PM](https://user-images.githubusercontent.com/8219193/155480348-3cdd56cd-ff71-40ef-ba53-b030faf55674.jpeg)

**Comment by Tiarakhaulah** [comment]
semua cust baru yg Pilih yes di Print VA , di kwitansi 
bukan nya keluar no VA nya malahan hilang tuh NO VA.

**Comment by andyut** [comment]
done by CNW_VA
