### ISSUE TITLE
CNW AWR 28 : Sales Order List ditambahin Sales 

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#42]
menu > Sales Analysit > Sales order lis 

Sales person msh blm ada ya pa andy di sales order list 
banyak yg request itu karena biar gampang tau itu customer punya sales siapa

**Comment by andyut** [comment]
Sales person apa sales group

**Comment by DikaAnggara89** [comment]
Sales person pak

Pada tanggal Sen, 7 Mar 2022 pukul 13.37 Andy Ut ***@***.***>
menulis:

**Comment by DikaAnggara89** [comment]
Sales Personnya pak

**Comment by andyut** [comment]
done
