### ISSUE TITLE
Solo issue (TERP)

### ISSUE THREAD

**Issue by igusmg** [andyut/cnw_project#48]
![WhatsApp Image 2022-04-11 at 10 15 40](https://user-images.githubusercontent.com/102205104/162660095-3f29e61c-f13c-4398-b283-67bc55bdd387.jpeg)
Pertama di Invoice pak, dia di kolom invoice masih bener total nya karna harga sudah termasuk ppn.

**Comment by andyut** [comment]
updating transP05.asp sql parameter

**Comment by andyut** [comment]
testing user

**Comment by andyut** [comment]
done

**Comment by andyut** [comment]
done , tested
