### ISSUE TITLE
Solo issue2

### ISSUE THREAD

**Issue by igusmg** [andyut/cnw_project#49]
![WhatsApp Image 2022-04-11 at 10 16 46](https://user-images.githubusercontent.com/102205104/162660431-38783719-caec-4b55-83b2-0983abe5f7d6.jpeg)
Setelah akan di print nanti munculnya seperti ini pak, dia total atas sama bawah beda, harusnya sama.

**Comment by andyut** [comment]
- [ ] cek transP05r.asp 
- [ ] cek transP05r.rpt

**Comment by andyut** [comment]
done
