### ISSUE TITLE
Solo issue3

### ISSUE THREAD

**Issue by igusmg** [andyut/cnw_project#50]
![WhatsApp Image 2022-04-11 at 10 18 57](https://user-images.githubusercontent.com/102205104/162660556-428cf5da-60e8-4b3c-b7c0-8e55913e4f1f.jpeg)
Ini untuk tagihan yg ada di bu tatik pak, contoh di sini TFP, dia ada di laporan saldo piutang customer..

**Comment by andyut** [comment]
- [ ] check sp RPT
- [ ] check SP incoming payment

**Comment by andyut** [comment]
done

**Comment by andyut** [comment]
ready for user testing

**Comment by andyut** [comment]
done
