### ISSUE TITLE
CNW INVOICE

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#58]
Untuk alamat yg terlampir atau tercetak di invoice hampir beberapa Customer Request atau minta diubah menjadi alamat Ship to bukan alamat NPWP lagi. Sudah ada surat resmi dari Pajak untuk perubahan ini 

Dari mba Ida Sarana

**Comment by andyut** [comment]
lagi diupdate di indoguna dst, tolong tanyain, berlaku semua company apa engga

**Comment by DikaAnggara89** [comment]
ya pak lg nunggu list nya dia bikin 
saya update dulu aja di github tkt lupa

**Comment by andyut** [comment]
done , ada tambahan CNW-FPUSAT
