### ISSUE TITLE
Aging

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#59]
Aging hutang request ka tata 
minta di upload di github pak
biar pa andy inget ktnya

**Comment by andyut** [comment]
masih trouble, angkanya beda dengan SAP

**Comment by andyut** [comment]
[
![Screenshot from 2022-10-05 09-32-43](https://user-images.githubusercontent.com/8219193/193967637-23a7b1fd-f178-4abc-a512-e8679e255e52.png)
](url)


udah sama angkanya ..tunggu update ke CNW
