### ISSUE TITLE
Permintaan Mba nia  

### ISSUE THREAD

**Issue by RIOGANTENG97** [andyut/cnw_project#60]
mba nia minta rilis stock di SAP

**Comment by andyut** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [error](https://trello.com/c/xK84JZ8w/1-error)

**Comment by andyut** [comment]
escalate to IntiData

**Comment by andyut** [comment]
done di intidata, tinggal monitor lagi ada issue atau tidak
