### ISSUE TITLE
Penjualan di CNW dengan di SAP B1 berbeda

### ISSUE THREAD

**Issue by DikaAnggara89** [andyut/cnw_project#61]
<img width="925" alt="Screenshot_1" src="https://user-images.githubusercontent.com/95201017/171545511-e1ec3538-e4cd-4780-a258-d36e5afdd6e2.png">
Ka rina sarana kulina nanya pak kenapa berbeda penjualan detail di cnw dengan profit lost di sap b1
lebih besar di cnw .. tapi kalo dicocokin sm pajak yg lebih mendekati yg dari cnw hanya - mines dikit
<img width="954" alt="Screenshot_2" src="https://user-images.githubusercontent.com/95201017/171545708-dc4f90f0-aef2-4501-9c79-2c568911d760.png">

**Comment by DikaAnggara89** [comment]
tiap bulan jg beda pak saya coba tarik ga pernah sama ., 1 bulan 1 bulan saya coba tarik selalu lebih besar di cnw daripada di sap b1

**Comment by andyut** [comment]
cek dengan sales analysis SAP
